# coding: utf-8

"""
    Chemically Peculiar Stars Database OpenAPI definitions

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from openapi_client.configuration import Configuration


class Motion(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'star': 'Star',
        'datasource': 'DataSource',
        'proper_motion_ra': 'float',
        'proper_motion_ra_error': 'float',
        'proper_motion_dec': 'float',
        'proper_motion_dec_error': 'float',
        'parallax': 'float',
        'parallax_error': 'float',
        'defined': 'bool'
    }

    attribute_map = {
        'id': 'id',
        'star': 'star',
        'datasource': 'datasource',
        'proper_motion_ra': 'properMotionRa',
        'proper_motion_ra_error': 'properMotionRaError',
        'proper_motion_dec': 'properMotionDec',
        'proper_motion_dec_error': 'properMotionDecError',
        'parallax': 'parallax',
        'parallax_error': 'parallaxError',
        'defined': 'defined'
    }

    def __init__(self, id=None, star=None, datasource=None, proper_motion_ra=None, proper_motion_ra_error=None, proper_motion_dec=None, proper_motion_dec_error=None, parallax=None, parallax_error=None, defined=None, local_vars_configuration=None):  # noqa: E501
        """Motion - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._star = None
        self._datasource = None
        self._proper_motion_ra = None
        self._proper_motion_ra_error = None
        self._proper_motion_dec = None
        self._proper_motion_dec_error = None
        self._parallax = None
        self._parallax_error = None
        self._defined = None
        self.discriminator = None

        self.id = id
        if star is not None:
            self.star = star
        self.datasource = datasource
        if proper_motion_ra is not None:
            self.proper_motion_ra = proper_motion_ra
        if proper_motion_ra_error is not None:
            self.proper_motion_ra_error = proper_motion_ra_error
        if proper_motion_dec is not None:
            self.proper_motion_dec = proper_motion_dec
        if proper_motion_dec_error is not None:
            self.proper_motion_dec_error = proper_motion_dec_error
        if parallax is not None:
            self.parallax = parallax
        if parallax_error is not None:
            self.parallax_error = parallax_error
        if defined is not None:
            self.defined = defined

    @property
    def id(self):
        """Gets the id of this Motion.  # noqa: E501


        :return: The id of this Motion.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Motion.


        :param id: The id of this Motion.  # noqa: E501
        :type id: int
        """
        if self.local_vars_configuration.client_side_validation and id is None:  # noqa: E501
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def star(self):
        """Gets the star of this Motion.  # noqa: E501


        :return: The star of this Motion.  # noqa: E501
        :rtype: Star
        """
        return self._star

    @star.setter
    def star(self, star):
        """Sets the star of this Motion.


        :param star: The star of this Motion.  # noqa: E501
        :type star: Star
        """

        self._star = star

    @property
    def datasource(self):
        """Gets the datasource of this Motion.  # noqa: E501


        :return: The datasource of this Motion.  # noqa: E501
        :rtype: DataSource
        """
        return self._datasource

    @datasource.setter
    def datasource(self, datasource):
        """Sets the datasource of this Motion.


        :param datasource: The datasource of this Motion.  # noqa: E501
        :type datasource: DataSource
        """
        if self.local_vars_configuration.client_side_validation and datasource is None:  # noqa: E501
            raise ValueError("Invalid value for `datasource`, must not be `None`")  # noqa: E501

        self._datasource = datasource

    @property
    def proper_motion_ra(self):
        """Gets the proper_motion_ra of this Motion.  # noqa: E501


        :return: The proper_motion_ra of this Motion.  # noqa: E501
        :rtype: float
        """
        return self._proper_motion_ra

    @proper_motion_ra.setter
    def proper_motion_ra(self, proper_motion_ra):
        """Sets the proper_motion_ra of this Motion.


        :param proper_motion_ra: The proper_motion_ra of this Motion.  # noqa: E501
        :type proper_motion_ra: float
        """

        self._proper_motion_ra = proper_motion_ra

    @property
    def proper_motion_ra_error(self):
        """Gets the proper_motion_ra_error of this Motion.  # noqa: E501


        :return: The proper_motion_ra_error of this Motion.  # noqa: E501
        :rtype: float
        """
        return self._proper_motion_ra_error

    @proper_motion_ra_error.setter
    def proper_motion_ra_error(self, proper_motion_ra_error):
        """Sets the proper_motion_ra_error of this Motion.


        :param proper_motion_ra_error: The proper_motion_ra_error of this Motion.  # noqa: E501
        :type proper_motion_ra_error: float
        """

        self._proper_motion_ra_error = proper_motion_ra_error

    @property
    def proper_motion_dec(self):
        """Gets the proper_motion_dec of this Motion.  # noqa: E501


        :return: The proper_motion_dec of this Motion.  # noqa: E501
        :rtype: float
        """
        return self._proper_motion_dec

    @proper_motion_dec.setter
    def proper_motion_dec(self, proper_motion_dec):
        """Sets the proper_motion_dec of this Motion.


        :param proper_motion_dec: The proper_motion_dec of this Motion.  # noqa: E501
        :type proper_motion_dec: float
        """

        self._proper_motion_dec = proper_motion_dec

    @property
    def proper_motion_dec_error(self):
        """Gets the proper_motion_dec_error of this Motion.  # noqa: E501


        :return: The proper_motion_dec_error of this Motion.  # noqa: E501
        :rtype: float
        """
        return self._proper_motion_dec_error

    @proper_motion_dec_error.setter
    def proper_motion_dec_error(self, proper_motion_dec_error):
        """Sets the proper_motion_dec_error of this Motion.


        :param proper_motion_dec_error: The proper_motion_dec_error of this Motion.  # noqa: E501
        :type proper_motion_dec_error: float
        """

        self._proper_motion_dec_error = proper_motion_dec_error

    @property
    def parallax(self):
        """Gets the parallax of this Motion.  # noqa: E501


        :return: The parallax of this Motion.  # noqa: E501
        :rtype: float
        """
        return self._parallax

    @parallax.setter
    def parallax(self, parallax):
        """Sets the parallax of this Motion.


        :param parallax: The parallax of this Motion.  # noqa: E501
        :type parallax: float
        """

        self._parallax = parallax

    @property
    def parallax_error(self):
        """Gets the parallax_error of this Motion.  # noqa: E501


        :return: The parallax_error of this Motion.  # noqa: E501
        :rtype: float
        """
        return self._parallax_error

    @parallax_error.setter
    def parallax_error(self, parallax_error):
        """Sets the parallax_error of this Motion.


        :param parallax_error: The parallax_error of this Motion.  # noqa: E501
        :type parallax_error: float
        """

        self._parallax_error = parallax_error

    @property
    def defined(self):
        """Gets the defined of this Motion.  # noqa: E501


        :return: The defined of this Motion.  # noqa: E501
        :rtype: bool
        """
        return self._defined

    @defined.setter
    def defined(self, defined):
        """Sets the defined of this Motion.


        :param defined: The defined of this Motion.  # noqa: E501
        :type defined: bool
        """

        self._defined = defined

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Motion):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Motion):
            return True

        return self.to_dict() != other.to_dict()
