# coding: utf-8

"""
    Chemically Peculiar Stars Database OpenAPI definitions

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from openapi_client.configuration import Configuration


class StarBasicInfo(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'id_2009_a_and_a_498_961_r': 'str',
        'considered_category_affiliation_probability_flag': 'str',
        'binary_system_component': 'str',
        'icrs_right_ascension': 'float',
        'icrs_declination': 'float',
        'galactic_longitude': 'float',
        'galactic_latitude': 'float'
    }

    attribute_map = {
        'id': 'id',
        'id_2009_a_and_a_498_961_r': 'id_2009_A_AND_A_498_961_R',
        'considered_category_affiliation_probability_flag': 'consideredCategoryAffiliationProbabilityFlag',
        'binary_system_component': 'binarySystemComponent',
        'icrs_right_ascension': 'icrsRightAscension',
        'icrs_declination': 'icrsDeclination',
        'galactic_longitude': 'galacticLongitude',
        'galactic_latitude': 'galacticLatitude'
    }

    def __init__(self, id=None, id_2009_a_and_a_498_961_r=None, considered_category_affiliation_probability_flag=None, binary_system_component=None, icrs_right_ascension=None, icrs_declination=None, galactic_longitude=None, galactic_latitude=None, local_vars_configuration=None):  # noqa: E501
        """StarBasicInfo - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._id_2009_a_and_a_498_961_r = None
        self._considered_category_affiliation_probability_flag = None
        self._binary_system_component = None
        self._icrs_right_ascension = None
        self._icrs_declination = None
        self._galactic_longitude = None
        self._galactic_latitude = None
        self.discriminator = None

        self.id = id
        if id_2009_a_and_a_498_961_r is not None:
            self.id_2009_a_and_a_498_961_r = id_2009_a_and_a_498_961_r
        if considered_category_affiliation_probability_flag is not None:
            self.considered_category_affiliation_probability_flag = considered_category_affiliation_probability_flag
        if binary_system_component is not None:
            self.binary_system_component = binary_system_component
        if icrs_right_ascension is not None:
            self.icrs_right_ascension = icrs_right_ascension
        if icrs_declination is not None:
            self.icrs_declination = icrs_declination
        if galactic_longitude is not None:
            self.galactic_longitude = galactic_longitude
        if galactic_latitude is not None:
            self.galactic_latitude = galactic_latitude

    @property
    def id(self):
        """Gets the id of this StarBasicInfo.  # noqa: E501


        :return: The id of this StarBasicInfo.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this StarBasicInfo.


        :param id: The id of this StarBasicInfo.  # noqa: E501
        :type id: int
        """
        if self.local_vars_configuration.client_side_validation and id is None:  # noqa: E501
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def id_2009_a_and_a_498_961_r(self):
        """Gets the id_2009_a_and_a_498_961_r of this StarBasicInfo.  # noqa: E501


        :return: The id_2009_a_and_a_498_961_r of this StarBasicInfo.  # noqa: E501
        :rtype: str
        """
        return self._id_2009_a_and_a_498_961_r

    @id_2009_a_and_a_498_961_r.setter
    def id_2009_a_and_a_498_961_r(self, id_2009_a_and_a_498_961_r):
        """Sets the id_2009_a_and_a_498_961_r of this StarBasicInfo.


        :param id_2009_a_and_a_498_961_r: The id_2009_a_and_a_498_961_r of this StarBasicInfo.  # noqa: E501
        :type id_2009_a_and_a_498_961_r: str
        """

        self._id_2009_a_and_a_498_961_r = id_2009_a_and_a_498_961_r

    @property
    def considered_category_affiliation_probability_flag(self):
        """Gets the considered_category_affiliation_probability_flag of this StarBasicInfo.  # noqa: E501


        :return: The considered_category_affiliation_probability_flag of this StarBasicInfo.  # noqa: E501
        :rtype: str
        """
        return self._considered_category_affiliation_probability_flag

    @considered_category_affiliation_probability_flag.setter
    def considered_category_affiliation_probability_flag(self, considered_category_affiliation_probability_flag):
        """Sets the considered_category_affiliation_probability_flag of this StarBasicInfo.


        :param considered_category_affiliation_probability_flag: The considered_category_affiliation_probability_flag of this StarBasicInfo.  # noqa: E501
        :type considered_category_affiliation_probability_flag: str
        """

        self._considered_category_affiliation_probability_flag = considered_category_affiliation_probability_flag

    @property
    def binary_system_component(self):
        """Gets the binary_system_component of this StarBasicInfo.  # noqa: E501


        :return: The binary_system_component of this StarBasicInfo.  # noqa: E501
        :rtype: str
        """
        return self._binary_system_component

    @binary_system_component.setter
    def binary_system_component(self, binary_system_component):
        """Sets the binary_system_component of this StarBasicInfo.


        :param binary_system_component: The binary_system_component of this StarBasicInfo.  # noqa: E501
        :type binary_system_component: str
        """

        self._binary_system_component = binary_system_component

    @property
    def icrs_right_ascension(self):
        """Gets the icrs_right_ascension of this StarBasicInfo.  # noqa: E501


        :return: The icrs_right_ascension of this StarBasicInfo.  # noqa: E501
        :rtype: float
        """
        return self._icrs_right_ascension

    @icrs_right_ascension.setter
    def icrs_right_ascension(self, icrs_right_ascension):
        """Sets the icrs_right_ascension of this StarBasicInfo.


        :param icrs_right_ascension: The icrs_right_ascension of this StarBasicInfo.  # noqa: E501
        :type icrs_right_ascension: float
        """

        self._icrs_right_ascension = icrs_right_ascension

    @property
    def icrs_declination(self):
        """Gets the icrs_declination of this StarBasicInfo.  # noqa: E501


        :return: The icrs_declination of this StarBasicInfo.  # noqa: E501
        :rtype: float
        """
        return self._icrs_declination

    @icrs_declination.setter
    def icrs_declination(self, icrs_declination):
        """Sets the icrs_declination of this StarBasicInfo.


        :param icrs_declination: The icrs_declination of this StarBasicInfo.  # noqa: E501
        :type icrs_declination: float
        """

        self._icrs_declination = icrs_declination

    @property
    def galactic_longitude(self):
        """Gets the galactic_longitude of this StarBasicInfo.  # noqa: E501


        :return: The galactic_longitude of this StarBasicInfo.  # noqa: E501
        :rtype: float
        """
        return self._galactic_longitude

    @galactic_longitude.setter
    def galactic_longitude(self, galactic_longitude):
        """Sets the galactic_longitude of this StarBasicInfo.


        :param galactic_longitude: The galactic_longitude of this StarBasicInfo.  # noqa: E501
        :type galactic_longitude: float
        """

        self._galactic_longitude = galactic_longitude

    @property
    def galactic_latitude(self):
        """Gets the galactic_latitude of this StarBasicInfo.  # noqa: E501


        :return: The galactic_latitude of this StarBasicInfo.  # noqa: E501
        :rtype: float
        """
        return self._galactic_latitude

    @galactic_latitude.setter
    def galactic_latitude(self, galactic_latitude):
        """Sets the galactic_latitude of this StarBasicInfo.


        :param galactic_latitude: The galactic_latitude of this StarBasicInfo.  # noqa: E501
        :type galactic_latitude: float
        """

        self._galactic_latitude = galactic_latitude

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StarBasicInfo):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, StarBasicInfo):
            return True

        return self.to_dict() != other.to_dict()
